spring:
  datasource:
    url: jdbc:mysql://49.234.37.181:3306/tob_libary?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: tob_libary
    password: tob_libary
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 150
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: false
    validation-query: SELECT 1
    validation-query-timeout: 500
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 30000
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
