server:
  port: 8800
  servlet:
    context-path: /shiyi

spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  profiles:
    active: dev  # ?????profile

  mail:
    host: smtp.qq.com #?????
    username: 196322385@qq.com #????????
    password: pyxafypgzufabicg #QQ??????
    port: 587 #???465-smtps?587-smtp
    from: 196322385@qq.com # ???????????username??
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      default-encoding: UTF-8
      protocol: smtp


  application:
    name: endless

# IP????
IpLimit:
  count: 10
  time: 10

# ?????
task:
  executor:
    core_pool_size: 10
    max_pool_size: 200
    queue_capacity: 1200
    keep_alive_seconds: 60

# ?????
wechat:
  app-id:
  secret:
  token:
  aesKey:

# Sa-Token??
sa-token:
  token-name: Authorization
  # token??????s ??30?, -1??????
  timeout: 86400
  activity-timeout: 600 # 10???????
  is-concurrent: true
  is-share: true
  token-style: random-128
  is-log: false

# mybatis-plus??
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #???????package?????????
  typeAliasesPackage: com.shiyi.entity
  global-config:
    # ???????
    db-config:
      #????  AUTO:"???ID??", INPUT:"????ID",ID_WORKER:"????ID (??????ID)", UUID:"????ID UUID";
      id-type: AUTO
      #???? IGNORED:"????",NOT_NULL:"? NULL ??"),NOT_EMPTY:"????"
      field-strategy: not_empty
      #???????
      column-underline: true
      db-type: mysql
    #??mapper ????
    refresh: true
  # ????
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Knife4j??
knife4j:
  enable: true
  basic:
    enable: true
    username: admin
    password:

# mybatis ????
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
